plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.foodiego'
    compileSdk 35

    defaultConfig {
        applicationId 'com.foodiego'
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

flutter {
    source '../..'
}
